---
require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - bin/*
    - lib/ovh-rest.rb

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
